-- Fix all enums by adding missing values
-- Run this in Supabase Dashboard SQL Editor

ALTER TYPE property_type ADD VALUE IF NOT EXISTS 'APARTMENT';
ALTER TYPE property_type ADD VALUE IF NOT EXISTS 'VILLA';
ALTER TYPE property_type ADD VALUE IF NOT EXISTS 'COMMERCIAL';
ALTER TYPE property_type ADD VALUE IF NOT EXISTS 'LAND';

ALTER TYPE property_status ADD VALUE IF NOT EXISTS 'AVAILABLE';
ALTER TYPE property_status ADD VALUE IF NOT EXISTS 'SOLD';
ALTER TYPE property_status ADD VALUE IF NOT EXISTS 'RENTED';
ALTER TYPE property_status ADD VALUE IF NOT EXISTS 'UNDER_OFFER';
ALTER TYPE property_status ADD VALUE IF NOT EXISTS 'UNDER_CONSTRUCTION';

ALTER TYPE ticket_status ADD VALUE IF NOT EXISTS 'OPEN';
ALTER TYPE ticket_status ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE ticket_status ADD VALUE IF NOT EXISTS 'RESOLVED';
ALTER TYPE ticket_status ADD VALUE IF NOT EXISTS 'CLOSED';

ALTER TYPE ticket_channel ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE ticket_channel ADD VALUE IF NOT EXISTS 'WHATSAPP';
ALTER TYPE ticket_channel ADD VALUE IF NOT EXISTS 'WEB_PORTAL';

ALTER TYPE campaign_type ADD VALUE IF NOT EXISTS 'SMS';
ALTER TYPE campaign_type ADD VALUE IF NOT EXISTS 'EMAIL';
ALTER TYPE campaign_type ADD VALUE IF NOT EXISTS 'WHATSAPP';

ALTER TYPE campaign_status ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE campaign_status ADD VALUE IF NOT EXISTS 'SCHEDULED';
ALTER TYPE campaign_status ADD VALUE IF NOT EXISTS 'RUNNING';
ALTER TYPE campaign_status ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE campaign_status ADD VALUE IF NOT EXISTS 'PAUSED';
ALTER TYPE campaign_status ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TYPE call_direction ADD VALUE IF NOT EXISTS 'INBOUND';
ALTER TYPE call_direction ADD VALUE IF NOT EXISTS 'OUTBOUND';

ALTER TYPE call_status ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE call_status ADD VALUE IF NOT EXISTS 'MISSED';
ALTER TYPE call_status ADD VALUE IF NOT EXISTS 'BUSY';
ALTER TYPE call_status ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE call_status ADD VALUE IF NOT EXISTS 'RINGING';

ALTER TYPE attendance_status ADD VALUE IF NOT EXISTS 'PRESENT';
ALTER TYPE attendance_status ADD VALUE IF NOT EXISTS 'ABSENT';
ALTER TYPE attendance_status ADD VALUE IF NOT EXISTS 'LATE';
ALTER TYPE attendance_status ADD VALUE IF NOT EXISTS 'HALF_DAY';
ALTER TYPE attendance_status ADD VALUE IF NOT EXISTS 'HOLIDAY';
ALTER TYPE attendance_status ADD VALUE IF NOT EXISTS 'LEAVE';

ALTER TYPE leave_status ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE leave_status ADD VALUE IF NOT EXISTS 'APPROVED';
ALTER TYPE leave_status ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE leave_status ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'SICK';
ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'CASUAL';
ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'ANNUAL';
ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'MATERNITY';
ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'PATERNITY';
ALTER TYPE leave_type ADD VALUE IF NOT EXISTS 'UNPAID';

ALTER TYPE product_category ADD VALUE IF NOT EXISTS 'MENS_WEAR';
ALTER TYPE product_category ADD VALUE IF NOT EXISTS 'WOMENS_WEAR';
ALTER TYPE product_category ADD VALUE IF NOT EXISTS 'KIDS_WEAR';
ALTER TYPE product_category ADD VALUE IF NOT EXISTS 'ACCESSORIES';
ALTER TYPE product_category ADD VALUE IF NOT EXISTS 'FOOTWEAR';

ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'CONFIRMED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'SHIPPED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'DELIVERED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE order_status ADD VALUE IF NOT EXISTS 'RETURNED';

ALTER TYPE commission_status ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE commission_status ADD VALUE IF NOT EXISTS 'PAID';
ALTER TYPE commission_status ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'PENDING';
ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'PAID';
ALTER TYPE payment_status ADD VALUE IF NOT EXISTS 'CANCELLED';

ALTER TYPE interest_level ADD VALUE IF NOT EXISTS 'LOW';
ALTER TYPE interest_level ADD VALUE IF NOT EXISTS 'MEDIUM';
ALTER TYPE interest_level ADD VALUE IF NOT EXISTS 'HIGH';
ALTER TYPE interest_level ADD VALUE IF NOT EXISTS 'VERY_HIGH';

ALTER TYPE interest_status ADD VALUE IF NOT EXISTS 'INTERESTED';
ALTER TYPE interest_status ADD VALUE IF NOT EXISTS 'NEGOTIATING';
ALTER TYPE interest_status ADD VALUE IF NOT EXISTS 'BOOKED';
ALTER TYPE interest_status ADD VALUE IF NOT EXISTS 'LOST';
ALTER TYPE interest_status ADD VALUE IF NOT EXISTS 'NOT_INTERESTED';

ALTER TYPE viewing_status ADD VALUE IF NOT EXISTS 'SCHEDULED';
ALTER TYPE viewing_status ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE viewing_status ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE viewing_status ADD VALUE IF NOT EXISTS 'NO_SHOW';

-- Lowercase enums from schema.sql
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'manual_entry';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'website_form';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'facebook';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'google_ads';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'linkedin_ads';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'walk_in';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'csv_upload';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'api_integration';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'instagram';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'linkedin';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'referral';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'ivr_calls';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'whatsapp';
ALTER TYPE lead_source ADD VALUE IF NOT EXISTS 'email_campaign';
